name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x

    # Build and publish BiUM.Core
    - name: Build BiUM.Core
      run: dotnet build ./src/BiUM.Core/BiUM.Core.csproj -c Release
    - name: Pack BiUM.Core
      run: dotnet pack ./src/BiUM.Core/BiUM.Core.csproj -c Release -o nupkg
    - name: Publish BiUM.Core
      run: dotnet nuget push ./src/BiUM.Core/bin/Release/*.nupkg --source "https://nuget.pkg.github.com/hadevnet/index.json" -k ${{ secrets.GITHUB_TOKEN }}

    # Build and publish BiUM.Infrastructure
    - name: Build BiUM.Infrastructure
      run: dotnet build ./src/BiUM.Infrastructure/BiUM.Infrastructure.csproj -c Release
    - name: Pack BiUM.Infrastructure
      run: dotnet pack ./src/BiUM.Infrastructure/BiUM.Infrastructure.csproj -c Release -o nupkg
    - name: Publish BiUM.Infrastructure
      run: dotnet nuget push ./src/BiUM.Infrastructure/bin/Release/*.nupkg --source "https://nuget.pkg.github.com/hadevnet/index.json" -k ${{ secrets.GITHUB_TOKEN }}

    # Build and publish BiUM.Specialized
    - name: Build BiUM.Specialized
      run: dotnet build ./src/BiUM.Specialized/BiUM.Specialized.csproj -c Release
    - name: Pack BiUM.Specialized
      run: dotnet pack ./src/BiUM.Specialized/BiUM.Specialized.csproj -c Release -o nupkg
    - name: Publish BiUM.Specialized
      run: dotnet nuget push ./src/BiUM.Specialized/bin/Release/*.nupkg --source "https://nuget.pkg.github.com/hadevnet/index.json" -k ${{ secrets.GITHUB_TOKEN }}

    # Restore dependencies after publishing internal packages
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Debug
    - name: Test
      run: dotnet test --no-build --verbosity normal
